[package]
name = "safecopy"
version = "0.1.0"
authors = ["Timo von Holtz <tvh@tvholtz.de>"]
edition = "2021"

[dependencies]
bincode = "^0.9"
serde = "^1.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"